---
- hosts: BDCOM_SW
  gather_facts: no
  vars:
    backup_dir: "/root/network/backups/BDCOM"
  tasks:

    - name: Ensure Telnet client is available
      ansible.builtin.shell: whereis telnet | awk '{print $2}'
      run_once: yes
      register: telnet_check
      delegate_to: localhost

    - ansible.builtin.fail:
        msg: >-
          Telnet client is not installed on the control node.
          Please install it and re-run the playbook.
      when: telnet_check.stdout | length == 0

    - name: Collect full output of both commands over Telnet
      ansible.builtin.shell: >-
        (
        echo '{{ ansible_user }}'; 
        sleep 1; 
        echo '{{ ansible_ssh_pass }}'; 
        sleep 1; 
        echo "enable"; 
        sleep 1; 
        echo "terminal length 0"; 
        sleep 1; 
        echo "show interface brief"; 
        sleep 2; 
        echo "show configuration"; 
        sleep 5; 
        echo "exit"
        ) | telnet {{ inventory_hostname }} {{ ansible_port | default(23) }}
      register: combined_output
      delegate_to: localhost

    - name: Store full output to a local file
      ansible.builtin.copy:
        content: "{{ combined_output.stdout }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}_full_output_{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}.txt"
      when: combined_output is defined
      delegate_to: localhost
