---
- name: Huawei Backup Playbook
  hosts: localhost
  tasks:
    - name: Activate virtual environment and execute Python script
      shell: |
        source /root/network/pythonproject/env/bin/activate
        python3 /root/network/pythonproject/script/huawei_backup.py
      args:
        executable: /bin/bash
