---
- hosts: DUDE_RTR
  gather_facts: no
  vars:
    backup_dir: "/root/network/backups/DUDE_RTR"
    ts: "{{ lookup('pipe', 'date +%Y-%m-%d@%H-%M-%S') }}"
  tasks:
    - name: Ensure local backup directory exists
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: yes

    - name: Set default SSH port (22 if undefined)
      set_fact:
        ansible_port: "{{ ansible_port | default(22) }}"

    - name: Define filenames
      set_fact:
        dude_bkp_name: "{{ inventory_hostname }}-dude-{{ ts }}.db"
        cfg_exp_name: "{{ inventory_hostname }}-config-{{ ts }}"

    - name: Run with password (if ansible_ssh_pass is defined)
      when: ansible_ssh_pass is defined
      block:
        - name: Ensure sshpass present
          ansible.builtin.shell: "whereis sshpass | awk '{print $2}'"
          run_once: yes
          register: sshpass
          delegate_to: localhost

        - name: Fail if sshpass missing
          ansible.builtin.fail:
            msg: "Install sshpass to use password auth."
          when: sshpass.stdout | length == 0

        - name: Export Dude DB on device
          ansible.builtin.shell: >-
            sshpass -p '{{ ansible_ssh_pass }}' ssh -o StrictHostKeyChecking=no -p {{ ansible_port }}
            {{ ansible_user }}@{{ inventory_hostname }}
            "/dude export-db backup-file={{ dude_bkp_name }}"
          delegate_to: localhost

        - name: Export config (.rsc) on device
          ansible.builtin.shell: >-
            sshpass -p '{{ ansible_ssh_pass }}' ssh -o StrictHostKeyChecking=no -p {{ ansible_port }}
            {{ ansible_user }}@{{ inventory_hostname }}
            "/export file={{ cfg_exp_name }}"
          delegate_to: localhost

        - name: Download Dude DB
          ansible.builtin.shell: >-
            sshpass -p '{{ ansible_ssh_pass }}' scp -P {{ ansible_port }} -o StrictHostKeyChecking=no
            {{ ansible_user }}@{{ inventory_hostname }}:{{ dude_bkp_name }} {{ backup_dir }}/
          delegate_to: localhost

        - name: Download config export
          ansible.builtin.shell: >-
            sshpass -p '{{ ansible_ssh_pass }}' scp -P {{ ansible_port }} -o StrictHostKeyChecking=no
            {{ ansible_user }}@{{ inventory_hostname }}:{{ cfg_exp_name }}.rsc {{ backup_dir }}/
          delegate_to: localhost

    - name: Run with key (if ansible_ssh_pass is not defined)
      when: ansible_ssh_pass is not defined
      block:
        - name: Export Dude DB on device
          ansible.builtin.shell: >-
            ssh -o StrictHostKeyChecking=no -p {{ ansible_port }}
            {{ ansible_user }}@{{ inventory_hostname }}
            "/dude export-db backup-file={{ dude_bkp_name }}"
          delegate_to: localhost

        - name: Export config (.rsc) on device
          ansible.builtin.shell: >-
            ssh -o StrictHostKeyChecking=no -p {{ ansible_port }}
            {{ ansible_user }}@{{ inventory_hostname }}
            "/export file={{ cfg_exp_name }}"
          delegate_to: localhost

        - name: Download Dude DB
          ansible.builtin.shell: >-
            scp -P {{ ansible_port }} -o StrictHostKeyChecking=no
            {{ ansible_user }}@{{ inventory_hostname }}:{{ dude_bkp_name }} {{ backup_dir }}/
          delegate_to: localhost

        - name: Download config export
          ansible.builtin.shell: >-
            scp -P {{ ansible_port }} -o StrictHostKeyChecking=no
            {{ ansible_user }}@{{ inventory_hostname }}:{{ cfg_exp_name }}.rsc {{ backup_dir }}/
          delegate_to: localhost
